// Mocks generated by Mockito 5.4.6 from annotations
// in macrotrace/test/presentation/bloc/meals_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:macrotrace/data/datasources/local_data_source.dart' as _i7;
import 'package:macrotrace/domain/entities/food_item.dart' as _i9;
import 'package:macrotrace/domain/entities/meal.dart' as _i10;
import 'package:macrotrace/domain/repositories/meal_repository.dart' as _i2;
import 'package:macrotrace/domain/services/date_time_service.dart' as _i6;
import 'package:macrotrace/domain/services/id_service.dart' as _i3;
import 'package:macrotrace/domain/usecases/get_all_meals.dart' as _i11;
import 'package:macrotrace/domain/usecases/get_daily_summary.dart' as _i13;
import 'package:macrotrace/domain/usecases/get_food_items.dart' as _i12;
import 'package:macrotrace/presentation/navigation/navigation_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealRepository_1 extends _i1.SmartFake
    implements _i2.MealRepository {
  _FakeMealRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdService extends _i1.Mock implements _i3.IdService {
  MockIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateId() =>
      (super.noSuchMethod(
            Invocation.method(#generateId, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#generateId, []),
            ),
          )
          as String);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i5.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void back() => super.noSuchMethod(
    Invocation.method(#back, []),
    returnValueForMissingStub: null,
  );

  @override
  void goHome() => super.noSuchMethod(
    Invocation.method(#goHome, []),
    returnValueForMissingStub: null,
  );

  @override
  void mealPage(String? mealId) => super.noSuchMethod(
    Invocation.method(#mealPage, [mealId]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i6.DateTimeService {
  MockDateTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime getToday() =>
      (super.noSuchMethod(
            Invocation.method(#getToday, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#getToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getYesterday() =>
      (super.noSuchMethod(
            Invocation.method(#getYesterday, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#getYesterday, []),
            ),
          )
          as DateTime);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i7.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<void> get mealsUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#mealsUpdated),
            returnValue: _i8.Stream<void>.empty(),
          )
          as _i8.Stream<void>);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i9.FoodItem>> getFoodItems() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodItems, []),
            returnValue: _i8.Future<List<_i9.FoodItem>>.value(<_i9.FoodItem>[]),
          )
          as _i8.Future<List<_i9.FoodItem>>);

  @override
  _i8.Future<List<_i10.Meal>> getAllMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMeals, []),
            returnValue: _i8.Future<List<_i10.Meal>>.value(<_i10.Meal>[]),
          )
          as _i8.Future<List<_i10.Meal>>);

  @override
  _i8.Future<void> saveMeal(_i10.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeal, [meal]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetAllMeals].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMeals extends _i1.Mock implements _i11.GetAllMeals {
  MockGetAllMeals() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMealRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MealRepository);

  @override
  _i8.Future<List<_i10.Meal>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i8.Future<List<_i10.Meal>>.value(<_i10.Meal>[]),
          )
          as _i8.Future<List<_i10.Meal>>);
}

/// A class which mocks [GetFoodItems].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodItems extends _i1.Mock implements _i12.GetFoodItems {
  MockGetFoodItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMealRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MealRepository);

  @override
  _i8.Future<List<_i9.FoodItem>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i8.Future<List<_i9.FoodItem>>.value(<_i9.FoodItem>[]),
          )
          as _i8.Future<List<_i9.FoodItem>>);
}

/// A class which mocks [GetDailySummary].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailySummary extends _i1.Mock implements _i13.GetDailySummary {
  MockGetDailySummary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, double> call({
    required List<_i10.Meal>? mealsForDay,
    required List<_i9.FoodItem>? allFoodItems,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #mealsForDay: mealsForDay,
              #allFoodItems: allFoodItems,
            }),
            returnValue: <String, double>{},
          )
          as Map<String, double>);
}

/// A class which mocks [MealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRepository extends _i1.Mock implements _i2.MealRepository {
  MockMealRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<void> get mealsUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#mealsUpdated),
            returnValue: _i8.Stream<void>.empty(),
          )
          as _i8.Stream<void>);

  @override
  _i8.Future<List<_i9.FoodItem>> getFoodItems() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodItems, []),
            returnValue: _i8.Future<List<_i9.FoodItem>>.value(<_i9.FoodItem>[]),
          )
          as _i8.Future<List<_i9.FoodItem>>);

  @override
  _i8.Future<List<_i10.Meal>> getAllMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMeals, []),
            returnValue: _i8.Future<List<_i10.Meal>>.value(<_i10.Meal>[]),
          )
          as _i8.Future<List<_i10.Meal>>);

  @override
  _i8.Future<void> saveMeal(_i10.Meal? meal) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeal, [meal]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
