// Mocks generated by Mockito 5.4.6 from annotations
// in macrotrace/test/presentation/bloc/meals_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:macrotrace/data/datasources/local_data_source.dart' as _i4;
import 'package:macrotrace/domain/entities/food_item.dart' as _i6;
import 'package:macrotrace/domain/entities/meal.dart' as _i7;
import 'package:macrotrace/domain/repositories/meal_repository.dart' as _i2;
import 'package:macrotrace/domain/services/date_time_service.dart' as _i3;
import 'package:macrotrace/domain/usecases/get_all_meals.dart' as _i8;
import 'package:macrotrace/domain/usecases/get_daily_summary.dart' as _i10;
import 'package:macrotrace/domain/usecases/get_food_items.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealRepository_1 extends _i1.SmartFake
    implements _i2.MealRepository {
  _FakeMealRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i3.DateTimeService {
  MockDateTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime getToday() =>
      (super.noSuchMethod(
            Invocation.method(#getToday, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#getToday, []),
            ),
          )
          as DateTime);

  @override
  DateTime getYesterday() =>
      (super.noSuchMethod(
            Invocation.method(#getYesterday, []),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#getYesterday, []),
            ),
          )
          as DateTime);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i4.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.FoodItem>> getFoodItems() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodItems, []),
            returnValue: _i5.Future<List<_i6.FoodItem>>.value(<_i6.FoodItem>[]),
          )
          as _i5.Future<List<_i6.FoodItem>>);

  @override
  _i5.Future<List<_i7.Meal>> getAllMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMeals, []),
            returnValue: _i5.Future<List<_i7.Meal>>.value(<_i7.Meal>[]),
          )
          as _i5.Future<List<_i7.Meal>>);
}

/// A class which mocks [GetAllMeals].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMeals extends _i1.Mock implements _i8.GetAllMeals {
  MockGetAllMeals() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMealRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MealRepository);

  @override
  _i5.Future<List<_i7.Meal>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i7.Meal>>.value(<_i7.Meal>[]),
          )
          as _i5.Future<List<_i7.Meal>>);
}

/// A class which mocks [GetFoodItems].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodItems extends _i1.Mock implements _i9.GetFoodItems {
  MockGetFoodItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMealRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MealRepository);

  @override
  _i5.Future<List<_i6.FoodItem>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i6.FoodItem>>.value(<_i6.FoodItem>[]),
          )
          as _i5.Future<List<_i6.FoodItem>>);
}

/// A class which mocks [GetDailySummary].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailySummary extends _i1.Mock implements _i10.GetDailySummary {
  MockGetDailySummary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, double> call({
    required List<_i7.Meal>? mealsForDay,
    required List<_i6.FoodItem>? allFoodItems,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #mealsForDay: mealsForDay,
              #allFoodItems: allFoodItems,
            }),
            returnValue: <String, double>{},
          )
          as Map<String, double>);
}
